# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - Andeuschland
  procesoApi:
    image: procesoapi
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 5000:5000
    networks:
      - Andeuschland
  procesobackend:
    image: procesobackend
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - Andeuschland
networks:
  Andeuschland:
