// <auto-generated />
using BDD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BDD.Migrations
{
    [DbContext(typeof(BaseTempoContext))]
    [Migration("20220121112959_BDDcreated")]
    partial class BDDcreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BDD.Localidades", b =>
                {
                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaFKProvincia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaRegionFKZona")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Localidad");

                    b.HasIndex("ProvinciaFKProvincia");

                    b.HasIndex("ZonaRegionFKZona");

                    b.ToTable("Localidad");
                });

            modelBuilder.Entity("BDD.Provincias", b =>
                {
                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Provincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("BDD.TemporalLocalidades", b =>
                {
                    b.Property<string>("Localidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Humedad")
                        .HasColumnType("float");

                    b.Property<string>("LocalidadFKLocalidad")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Precipitaciones")
                        .HasColumnType("float");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<double>("VelViento")
                        .HasColumnType("float");

                    b.HasKey("Localidad");

                    b.HasIndex("LocalidadFKLocalidad");

                    b.ToTable("TemporalLocalidad");
                });

            modelBuilder.Entity("BDD.ZonasRegion", b =>
                {
                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Zona");

                    b.ToTable("ZonaRegion");
                });

            modelBuilder.Entity("BDD.Localidades", b =>
                {
                    b.HasOne("BDD.Provincias", "ProvinciaFK")
                        .WithMany("LocalidadProv")
                        .HasForeignKey("ProvinciaFKProvincia");

                    b.HasOne("BDD.ZonasRegion", "ZonaRegionFK")
                        .WithMany("LocalidadRegi")
                        .HasForeignKey("ZonaRegionFKZona");

                    b.Navigation("ProvinciaFK");

                    b.Navigation("ZonaRegionFK");
                });

            modelBuilder.Entity("BDD.TemporalLocalidades", b =>
                {
                    b.HasOne("BDD.Localidades", "LocalidadFK")
                        .WithMany()
                        .HasForeignKey("LocalidadFKLocalidad");

                    b.Navigation("LocalidadFK");
                });

            modelBuilder.Entity("BDD.Provincias", b =>
                {
                    b.Navigation("LocalidadProv");
                });

            modelBuilder.Entity("BDD.ZonasRegion", b =>
                {
                    b.Navigation("LocalidadRegi");
                });
#pragma warning restore 612, 618
        }
    }
}
